spring:
  main:
    web-application-type: reactive

  profiles:
    active: default

  application:
    name: rempms-api-gateway-service
  config:
    import: "configserver:http://localhost:8071/"

logging:
  level:
    org:
      springframework:
        cloud: DEBUG